name = "Foxxo Demon Pack"
author = "hexagonelle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "104f98c078f036cfa4f263b8a097821b43f18a4e406714e5052b716cf9331b54"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
