name = "Foxxo Demon Pack"
author = "hexagonelle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "814553cd7f0dc4ca615234de0f410417a20935c7c55b64ea29ba3200efd86f78"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
