name = "Foxxo Demon Pack"
author = "hexagonelle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d190d01de36144540ddd8aa61909ecd934e852545eea4140e2d062237179d4eb"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
